version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BING_USER_TOKEN=${BING_USER_TOKEN}
    volumes:
      - ./settings.js:/var/chatgpt-api/settings.js:cached
    ports:
      - '${APP_PORT:-3000}:3000'
